config/routes.rb
WaterCounter::Application.routes.draw do
  resources :counters do
  collection do
    get :table
  end
end

  root 'counters#index'

  get 'counters/table'

  

end

app/models/counter.rb
class Counter < ActiveRecord::Base

  has_one :next_counter, :class_name => 'Counter',
          :foreign_key => 'prev_id',
          :inverse_of => :prev_counter

  belongs_to :prev_counter, :class_name => 'Counter',
             :foreign_key => 'prev_id',
             :inverse_of => :next_counter

  validates :date, :warm, :cold, presence: true
	validate :validate_calculations

  scope :earlier_than, lambda { |date| where('date < ?',  date).order('date') }
  scope :data, lambda { where('id > 2') }
  scope :years, lambda { select('year').data.group('year').order('date desc') }
  scope :year, lambda { |year| data.where(year: year) }

  before_validation :recalc

  def find_prev_record
	  Counter.earlier_than(date).last
  end

  def recalc
    x = find_prev_record

    self.year = self.date.year

    unless x.nil?
      self.prev_id = x.id
      self.warm_consumption = self.warm - x.warm
      self.cold_consumption = self.cold - x.cold
			self.prev_warm_consumption = x.warm_consumption
			self.prev_cold_consumption = x.cold_consumption

      return true
    end

    false
  end

	def validate_calculations
    if prev_id.nil?
			errors.add(:date, I18n.t('activerecord.validation.message1'))
		else
			errors.add(:warm, I18n.t('activerecord.validation.message2')%{p1: self.prev_counter.warm}) if warm_consumption <= 0
      errors.add(:cold, I18n.t('activerecord.validation.message2')%{p1: self.prev_counter.cold}) if cold_consumption <= 0
		end
	end

	def self.show_index
		joins(:prev_counter)
			.select('counters.*
								, prev_counters_counters.warm_consumption as prev_warm_consumption
								, prev_counters_counters.cold_consumption as prev_cold_consumption')
			.order('counters.date desc')
	end

  def self.get_chart_array
    data.order(:date).pluck(:date, :warm_consumption, :cold_consumption).map{|d,w,c| [d.advance(:months => -1).to_time(:utc).to_i*1000, w, c]}
  end

  def show
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy]

  # GET /counters
  # GET /counters.json
  def index
    #params[:year] ||= Counter.years[0].year
    #
    #@counters = Counter.year(params[:year]).order('date desc')
  end

  def table
    params[:year] ||= Counter.years[0].year

    @counters = Counter.year(params[:year]).order('date desc')

    respond_to do |format|
      format.js { render :layout=>false }
    end
  end


  # GET /counters/1
  # GET /counters/1.json
  def show
    @counter.show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @counter }
      else
        format.html { render action: 'new' }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.require(:counter).permit(:date, :warm, :cold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type] || flash_type.to_s
  end

  def bootstrap_class_for1 flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_chart.html.erb
<%
   chart_data = Counter.get_chart_array
%>
<script type="text/javascript">
    Highcharts.setOptions({
        lang: {
            shortMonths: ['янв', 'фев', 'мар', 'апр', 'май', 'июн',
                'июл', 'авг', 'сен', 'окт', 'ноя', 'дек']
        }
    });

    $(function () {
        $('#chart').highcharts({
            chart: {
                type: 'spline'
            },
            title: {
                text: 'Расход воды'
            },
            xAxis: {
                type: 'datetime',
                tickInterval: 24 * 3600 * 1000 *30 * 4,
                tickmarkPlacement: 'on',
                gridLineWidth: 1,
                gridLineDashStyle: 'dot',
                dateTimeLabelFormats: {
                    month: '%b %y',
                    year: '%Y'
                }
            },
            yAxis: {
                gridLineWidth: 0,
                title: {
                    text: 'Расход (м3)'
                },
                min: 0
            },
            tooltip: {
                formatter: function() {
                    return '<b>'+ this.series.name +'</b><br/>'+
                            Highcharts.dateFormat('%e %b %Y', this.x) +': '+ this.y +' m';
                }
            },

            series: [{
                name: 'горячая',
                color: 'red',
                data: <%= chart_data.map{|d,w,c| [d,w]} %>
            }, {
                name: 'холодная',
                color: 'blue',
                data: <%= chart_data.map{|d,w,c| [d,c]} %>
            }]
        });
    });
</script>
<div id="chart" style="width: 100%; height: 300px;"></div>

app/views/counters/_counter.html.erb
<tr class="overlay">
  <td class="date"><%= l counter.date.to_date, :format => :long %></td>

  <%
     wclass = counter.warm_consumption > counter.prev_warm_consumption ? 'more' : 'less'
     cclass = counter.cold_consumption > counter.prev_cold_consumption ? 'more' : 'less'
  %>

  <td class="warm"><%= counter.warm %> <span class="diff <%= wclass %>"><%= counter.warm_consumption %></span></td>
  <td class="cold"><%= counter.cold %> <span class="diff <%= cclass %>"><%= counter.cold_consumption %></span></td>

  <td class="b">
    <div class="btn-block">
      <%= link_to 'Квитанция', counter, :class => 'btn btn-info btn-xs show-doc' %>
      <%= link_to 'Править', edit_counter_path(counter), :class => 'btn btn-default btn-xs' %>
      <%= link_to 'Удалить', counter, method: :delete, data: { confirm: 'Вы уверены?' }, :class => 'btn btn-default btn-xs' %>
    </div>
  </td>
</tr>

app/views/counters/_counters_table.html.erb
<table class="counters-list table table-striped">
  <thead>
  <tr>
    <th><%= Counter.human_attribute_name('date') %></th>
    <th class="warm"><%= Counter.human_attribute_name('warm') %></th>
    <th class="cold"><%= Counter.human_attribute_name('cold') %></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <%= render @counters %>
  </tbody>
</table>

app/views/counters/_form.html.erb
<div class="row">
  <div class="col1-md-8">
    <%= simple_form_for(@counter, wrapper: :bootstrap3_horizontal,
                        defaults: {right_column_html: {class: "col-lg-3 col-md-3"},
                        label_html: {class: "col-lg-2 col-md-2"} },
                        html: {class: 'well form-horizontal', role: "form" }) do |f| %>

        <%= f.error_notification %>

        <legend>Показания счетчиков</legend>
        <%= f.input :date, as: :string, input_html: { value: Time.now.strftime('%d.%m.%Y'), data: {behaviour: "datepicker"} } %>
        <%= f.input :warm %>
        <%= f.input :cold %>

        <%= f.button :submit, { class: 'btn-primary' } %>
    <% end %>
  </div>
</div>

app/views/counters/_nav_bar.html.erb
<div class="container">
  <div class="btn-group">
    <%= link_to 'Новый месяц', new_counter_path, :class => "btn btn-primary" %>
  </div>

  <div class="pull-right">

    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span id="current_year"><%= params[:year] %></span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pull-right" role="menu">
        <%= render partial: 'year', collection: Counter.years %>
      </ul>
    </div>

  </div>
</div>

app/views/counters/_year.html.erb
<li><%= link_to year.year, counters_table_path(params.merge({ year: year.year})), remote: true %></li>

app/views/counters/edit.html.erb
<h1>Исправление месяца</h1>

<%= render 'form' %>

<%= link_to I18n.t('helpers.labels.back'), counters_path %>

app/views/counters/index.html.erb
<div class="page-header">
  <h1>Показания счетчиков</h1>
</div>

<%= render 'chart' %>

<%= render 'nav_bar' %>

<div id="counters_table" class="container">
</div>


<!--%= render 'counters_table' %-->


<% javascript_tag do %>
<% end %>

app/views/counters/new.html.erb
<h1>Новый месяц</h1>

<%= render 'form' %>

<%= link_to I18n.t('helpers.labels.back'), counters_path %>

app/views/counters/show.html.erb
<div class="show col-md-11">

<p class="top1">Согласовано ЕИРЦ</p>
<h1>Ведомость показаний квартирных приборов учета воды</h1>
<h2>за период с <%= l @counter.prev_counter.date.to_date, :format => :long %> по <%= l @counter.date.to_date, :format => :long %></h2>
  <div class="row">
    <div class="col-md-8">
        <p>Плательщик:  Фатеева И. И. телефон: 338-5428</p>
        <p>Проживающий по адресу: г.Москва, ул.Островитянова 16-2-75</p>
    </div>
    <div class="col-md-4">
        <p class="date1">Дата: <%= l @counter.date.to_date, :format => :long %></p>
    </div>
  </div>
<table>
  <tr><th colspan="3">Показания счетчика холодной воды</th><th colspan="3">Показания счетчика горячей воды</th></tr>
  <tr>
    <th>На начало периода</th>
    <th>На конец периода</th>
    <th>Расход за период</th>
    <th>На начало периода</th>
    <th>На конец периода</th>
    <th>Расход за период</th>
  </tr>
  <tr>
    <td><%= @counter.prev_counter.cold %> м<i>3</i></td>
    <td><%= @counter.cold %> м<i>3</i></td>
    <td><%= @counter.cold_consumption %> м<i>3</i></td>
    <td><%= @counter.prev_counter.warm %> м<i>3</i></td>
    <td><%= @counter.warm %> м<i>3</i></td>
    <td><%= @counter.warm_consumption %> м<i>3</i></td>
  </tr>
</table>


<div class="signature">
  <p class="l">Представитель ЕИРЦ _______________/_____________/</p>
  <p class="r">Плательщик _________________/ Фатеева И. И. /</p>
</div>


<ul class="pager">
    <li><%= link_to I18n.t('helpers.labels.back'), counters_path %></li>
    <li><%= link_to I18n.t('helpers.labels.edit'), edit_counter_path(@counter) %></li>
</ul>

</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaterCounter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<main role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= render partial: "layouts/flash_messages", flash: flash %>
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div>
</main>

</body>
</html>